import "dotenv/config";
import mongoose from "mongoose";
import Application from "./models/Application.js";

const samples = [
  {
    company: "Stripe",
    role: "Software Engineer Intern",
    status: "Interview",
    priority: "High",
    source: "Referral",
    location: "San Francisco, CA",
    appliedDate: "2026-01-15",
    followUpDate: "2026-05-28",
    expectedRounds: 5,
    rounds: [
      { name: "Recruiter Screen", status: "Passed", scheduledDate: "2026-02-01" },
      { name: "Technical OA", status: "Passed", scheduledDate: "2026-02-15" },
      { name: "Technical Interview", status: "Scheduled", scheduledDate: "2026-05-28" },
      { name: "Hiring Manager", status: "Pending" },
      { name: "Team Match", status: "Pending" },
    ],
  },
  {
    company: "Google",
    role: "SWE Intern",
    status: "Interview",
    priority: "High",
    source: "Company Site",
    location: "Mountain View, CA",
    appliedDate: "2026-02-10",
    salary: "$8,000/mo",
    expectedRounds: 4,
    rounds: [
      { name: "Resume Screen", status: "Passed" },
      { name: "Phone Interview", status: "Passed" },
      { name: "Onsite", status: "Scheduled", scheduledDate: "2026-06-02" },
      { name: "Team Fit", status: "Pending" },
    ],
  },
  {
    company: "Notion",
    role: "Frontend Intern",
    status: "Screening",
    priority: "Medium",
    source: "LinkedIn",
    location: "New York, NY",
    appliedDate: "2026-02-01",
    expectedRounds: 4,
    rounds: [
      { name: "Application Review", status: "Passed" },
      { name: "Recruiter Call", status: "Scheduled", scheduledDate: "2026-05-27" },
      { name: "Technical", status: "Pending" },
      { name: "Culture Fit", status: "Pending" },
    ],
  },
  {
    company: "Amazon",
    role: "SDE Intern",
    status: "Screening",
    priority: "High",
    source: "Handshake",
    location: "Seattle, WA",
    appliedDate: "2026-03-05",
    followUpDate: "2026-05-25",
    expectedRounds: 3,
    rounds: [
      { name: "OA", status: "Scheduled", scheduledDate: "2026-05-26" },
      { name: "Phone Screen", status: "Pending" },
      { name: "Virtual Onsite", status: "Pending" },
    ],
  },
  {
    company: "Microsoft",
    role: "Software Engineer Intern",
    status: "Applied",
    priority: "High",
    source: "Career Fair",
    location: "Redmond, WA",
    appliedDate: "2026-04-01",
    deadline: "2026-06-15",
    expectedRounds: 4,
    rounds: [],
  },
  {
    company: "OpenAI",
    role: "Research Engineer Intern",
    status: "Applied",
    priority: "High",
    source: "Referral",
    location: "San Francisco, CA",
    appliedDate: "2026-04-18",
    notes: "Referred by alumni — follow up in 2 weeks",
    expectedRounds: 5,
    rounds: [],
  },
  {
    company: "Databricks",
    role: "SWE Intern",
    status: "Applied",
    priority: "Medium",
    source: "Company Site",
    location: "Remote",
    appliedDate: "2026-03-10",
    deadline: "2026-05-30",
    expectedRounds: 3,
    rounds: [],
  },
  {
    company: "Netflix",
    role: "UI Engineer Intern",
    status: "Interview",
    priority: "Medium",
    source: "LinkedIn",
    location: "Los Gatos, CA",
    appliedDate: "2026-01-20",
    expectedRounds: 3,
    rounds: [
      { name: "Recruiter", status: "Passed" },
      { name: "Technical", status: "Passed" },
      { name: "Final Panel", status: "Scheduled", scheduledDate: "2026-05-30" },
    ],
  },
  {
    company: "Airbnb",
    role: "Full Stack Intern",
    status: "Interview",
    priority: "Medium",
    source: "LinkedIn",
    location: "San Francisco, CA",
    appliedDate: "2026-02-22",
    expectedRounds: 4,
    rounds: [
      { name: "Recruiter", status: "Passed" },
      { name: "Coding", status: "Scheduled", scheduledDate: "2026-05-29" },
      { name: "System Design", status: "Pending" },
      { name: "Values", status: "Pending" },
    ],
  },
  {
    company: "Coinbase",
    role: "Backend Intern",
    status: "Screening",
    priority: "Low",
    source: "Company Site",
    location: "Remote",
    appliedDate: "2026-04-10",
    expectedRounds: 3,
    rounds: [
      { name: "Recruiter Screen", status: "Scheduled", scheduledDate: "2026-05-24" },
      { name: "Technical", status: "Pending" },
      { name: "Final", status: "Pending" },
    ],
  },
  {
    company: "Meta",
    role: "Production Engineer Intern",
    status: "Rejected",
    priority: "Medium",
    source: "Handshake",
    location: "Menlo Park, CA",
    appliedDate: "2025-11-20",
    expectedRounds: 4,
    rounds: [
      { name: "OA", status: "Passed" },
      { name: "Phone Screen", status: "Passed" },
      { name: "Onsite Loop", status: "Failed", scheduledDate: "2026-01-10" },
    ],
  },
  {
    company: "Figma",
    role: "Product Design Intern",
    status: "Ghosted",
    priority: "Low",
    source: "LinkedIn",
    appliedDate: "2026-01-08",
    rounds: [
      { name: "Portfolio Review", status: "Completed" },
      { name: "Recruiter", status: "Pending" },
    ],
  },
  {
    company: "Cloudflare",
    role: "Systems Intern",
    status: "Offer",
    priority: "High",
    source: "Referral",
    location: "Austin, TX",
    appliedDate: "2025-12-05",
    salary: "$45/hr",
    expectedRounds: 3,
    rounds: [
      { name: "Recruiter", status: "Passed" },
      { name: "Technical", status: "Passed" },
      { name: "Final", status: "Passed" },
    ],
  },
  {
    company: "Snowflake",
    role: "Data Engineering Intern",
    status: "Offer",
    priority: "High",
    source: "Referral",
    location: "Remote",
    appliedDate: "2026-01-05",
    salary: "$52/hr",
    notes: "Deadline to accept: June 10",
    expectedRounds: 3,
    rounds: [
      { name: "Recruiter", status: "Passed" },
      { name: "Technical", status: "Passed" },
      { name: "Offer Call", status: "Passed" },
    ],
  },
  {
    company: "Shopify",
    role: "Backend Intern",
    status: "Applied",
    priority: "Medium",
    source: "Career Fair",
    location: "Toronto, ON",
    appliedDate: "2026-04-02",
    followUpDate: "2026-05-27",
  },
  {
    company: "Uber",
    role: "Mobile Intern",
    status: "Applied",
    priority: "Medium",
    source: "LinkedIn",
    location: "San Francisco, CA",
    appliedDate: "2026-04-15",
    deadline: "2026-06-01",
  },
  {
    company: "Anthropic",
    role: "ML Engineer Intern",
    status: "Screening",
    priority: "High",
    source: "Company Site",
    location: "San Francisco, CA",
    appliedDate: "2026-03-28",
    expectedRounds: 4,
    rounds: [
      { name: "Resume Review", status: "Passed" },
      { name: "Take-home", status: "Scheduled", scheduledDate: "2026-05-28" },
      { name: "Technical", status: "Pending" },
      { name: "Research Discussion", status: "Pending" },
    ],
  },
  {
    company: "Vercel",
    role: "Developer Advocate Intern",
    status: "Interview",
    priority: "Low",
    source: "Other",
    location: "Remote",
    appliedDate: "2026-02-14",
    expectedRounds: 3,
    rounds: [
      { name: "Intro Call", status: "Passed" },
      { name: "Writing Sample", status: "Passed" },
      { name: "Final Chat", status: "Pending" },
    ],
  },
  {
    company: "Robinhood",
    role: "Android Intern",
    status: "Withdrawn",
    priority: "Low",
    source: "Other",
    appliedDate: "2026-02-20",
    notes: "Accepted another offer",
  },
  {
    company: "Palantir",
    role: "Forward Deployed Intern",
    status: "Rejected",
    priority: "Medium",
    source: "Handshake",
    location: "Denver, CO",
    appliedDate: "2026-01-30",
    expectedRounds: 3,
    rounds: [
      { name: "OA", status: "Failed" },
    ],
  },
];

const uri = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/job-tracker";

await mongoose.connect(uri);
await Application.deleteMany({});
await Application.insertMany(samples);
console.log(`Seeded ${samples.length} demo applications.`);
await mongoose.disconnect();
